ALTER TABLE agents ADD COLUMN public_ip TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN country_code TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN region TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN city TEXT NOT NULL DEFAULT '';
ALTER TABLE agents ADD COLUMN timezone TEXT NOT NULL DEFAULT '';
